name: Repository mirroring

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_program_compilation:
    container:
      image: epitechcontent/epitest-docker:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check_program_compilation
        run: |
          cmake -B build
          cmake --build build

  push_to_mirror:
    needs: [check_program_compilation]
    name: Push repository to mirror
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        run: |
          ls && ls build
